"""Regenerate the chapter index at the top of table-of-contents.md.

The index is derived from the volume sections below it, so it cannot drift away
from them. Run it after changing any chapter; it rewrites in place between the
two markers and prints what changed.

For chapters that have been specified, the one-liner is the *elicited aim* -- the
question the class arrives at, in their words. For chapters that have not, it is
the topic gloss. Italics in the output therefore mean "this chapter has been
worked out"; roman means "this is still a title".
"""
import pathlib
import re
import sys

DOC = pathlib.Path(__file__).resolve().parent / 'table-of-contents.md'
TOP = '<!-- INDEX:BEGIN -->'
END = '<!-- INDEX:END -->'


def sections(t):
    """(heading, body) for every Volume, the Coda and the excursion."""
    parts = re.split(r'^## ', t, flags=re.M)
    for p in parts:
        head = p.splitlines()[0].strip()
        if head.startswith(('Volume', 'Coda', 'An excursion')):
            yield head, p


def chapters(body):
    """(number, title, one-liner, specified?) for each chapter in a section.

    Entries wrap across lines in both styles, so a chapter is a *block*: it runs
    from its numbered line to the next one, and the pieces inside get rejoined
    before anything is pulled out of them.
    """
    lines = body.splitlines()
    starts = [i for i, l in enumerate(lines) if re.match(r'^(\*\*)?\d+\. \S', l)]
    out = []
    for k, i in enumerate(starts):
        j = starts[k + 1] if k + 1 < len(starts) else len(lines)
        block = lines[i:j]

        # the header runs until the first bullet, blank line, quote or rule --
        # anything after that belongs to the chapter's detail or to the section
        head_end = next((n for n, l in enumerate(block)
                         if not l.strip() or l.lstrip().startswith(('- ', '>', '---'))),
                        len(block))
        head = ' '.join(x.strip() for x in block[:head_end] if x.strip())
        m = re.match(r'^(?:\*\*)?(\d+)\.\s+(.*)$', head)
        num, rest = m.group(1), m.group(2)
        title, _, gloss = rest.partition('—')
        title = title.strip().strip('*').strip()
        gloss = gloss.strip()

        # the aim, if there is one, also wraps
        aim = ''
        for n, l in enumerate(block):
            if l.lstrip().startswith('- *Aim:*'):
                tail = [l]
                for nxt in block[n + 1:]:
                    if nxt.lstrip().startswith('- ') or not nxt.strip():
                        break
                    tail.append(nxt)
                joined = ' '.join(x.strip() for x in tail)
                a = re.search(r'\*Aim:\*\s*\*\*(.+?)\*\*', joined)
                if a:
                    aim = a.group(1)
                break

        out.append((num, title, aim or gloss, bool(aim)))
    return out


def build(t):
    rows = ['## Every chapter', '',
            '*Generated by `docs/toc_index.py` from the volumes below — do not edit by hand.*',
            '*An italic one-liner is the question the class arrives at, which means the chapter',
            'has been worked out. Roman means it is still only a title.*', '']
    n_spec = n_tot = n_req = 0
    for head, body in sections(t):
        ch = chapters(body)
        if not ch:
            continue
        rows.append(f'**{head}**')
        rows.append('')
        for num, title, one, spec in ch:
            n_tot += 1
            n_req += head.startswith('Volume')
            n_spec += spec
            one = re.sub(r'\s+', ' ', one).rstrip('.')
            if not one:
                rows.append(f'{num}. {title}')
            elif spec:
                rows.append(f'{num}. {title} — *{one}*')
            else:
                rows.append(f'{num}. {title} — {one}')
        rows.append('')
    rows.append(f'**{n_spec} of {n_req} chapters in the required sequence are worked out** '
                f'— a do-now, what goes wrong, and an elicited aim. '
                f'The Coda and the excursion are optional and add {n_tot - n_req} more.')
    rows.append('')
    return '\n'.join(rows), n_spec, n_tot


def main():
    t = DOC.read_text()
    body, spec, tot = build(t)
    if TOP in t:
        t = re.sub(re.escape(TOP) + r'.*?' + re.escape(END), TOP + '\n\n' + body + '\n' + END,
                   t, flags=re.S)
    else:
        anchor = '## What it is for'
        assert t.count(anchor) == 1
        t = t.replace(anchor, TOP + '\n\n' + body + '\n' + END + '\n\n---\n\n' + anchor, 1)
    DOC.write_text(t)
    print(f'index regenerated: {spec} of {tot} chapters worked out')


if __name__ == '__main__':
    main()
